### PR TITLE
Fixed handling of auto links

### LINKED ISSUE #10: Assertion fails for automatic links
The following markdown creates an assertion failure at https://github.com/soffes/MarkdownKit/blob/769ec26ac46fe9cd249c1fd6133b225102efa7ed/Sources/MarkdownKitObjC/BaseTextStorage.m#L27

```
This is an automatic link <http://www.w3.org/>
```

### PR DESCRIPTION
**Pull request by haldun**
Closes #10

### CODE REVIEW

File: Sources/MarkdownKit/Models/Nodes/Link.swift [hunk 1]
```diff
@@ -11,18 +11,33 @@ public class Link: Node {
...
+        }
+
         return NSRange(location: NSMaxRange(childRange) + 2, length: (url.absoluteString as NSString).length)
     }
 
     public var title: String? {
         cmark_node_get_title(node).map(String.init)
     }
 
+    public var isAutolink: Bool {
```
Comment (eliperkins) [inline Sources/MarkdownKit/Models/Nodes/Link.swift]: Does this need to be public? I'm not sure what the use-case would be for consumers of this, given that `MarkdownKit.Link` abstracts over both `[]()` style links and these autolinks.

**Review by eliperkins — APPROVED** [review]
This LGTM, since tests are passing! TIL that `<>` makes "autolinks"

File: Sources/MarkdownKit/Models/Nodes/Link.swift (hunk 1 above)
Comment (haldun) [reply Sources/MarkdownKit/Models/Nodes/Link.swift]: Nope, I guess `internal` makes more sense here, what do you think `internal` or `private`?

Comment (eliperkins) [reply Sources/MarkdownKit/Models/Nodes/Link.swift]: I think `internal` is fine if we care about the test case that uses it differentiating between autolinks and explicit links.  My gut says that since the two tests are named `testLinkDelimiters` and `testAutomaticLinks`, and the strings in those tests are explicitly different, that making this `private` should be fine.

**Review by soffes — APPROVED** [review]

**Comment by soffes** [comment]
Thanks everyone!

**Comment by soffes** [comment]
Released in 0.3.6

File: Sources/MarkdownKit/Models/Nodes/Link.swift (hunk 1 above)
Comment (soffes) [reply Sources/MarkdownKit/Models/Nodes/Link.swift]: I made it public in a later commit 🤷

Comment (soffes) [reply Sources/MarkdownKit/Models/Nodes/Link.swift]: (The rationale was maybe you'd want to style it differently than regular links so expose the data and let people decide.)
